# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install kivy[base] kivy_examples --pre --extra-index-url https://kivy.org/downloads/simple/.
        pip install ffpyplayer
        pip install numpy
        pip install pandas
        pip install xlsxwriter
        pip install PyInstaller
        ls
        python -m PyInstaller --hiddenimport win32timezone -F --name E-OATS_Application --icon Asset\ust_icon.ico main.py
        
        python -m PyInstaller E-OATS_Application.spec
    - name: Zip Release
      uses: TheDoctor0/zip-release@v0.3.0
      with:
        # Filename for archive
        filename: Application.zip
        # Base path for archive files
        path: /home/runner/work/E-OATS/E-OATS/dist/E-OATS_Application/
        # Working directory before zipping
        directory: /home/runner/work/E-OATS/E-OATS/dist/
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Application
        # A file, directory or wildcard pattern that describes what to upload
        path: /home/runner/work/E-OATS/E-OATS/dist/
    
  
